#!/bin/bash

RECEIVEJS=./receive.js
RECEIVEPY=receive.py
ARGS="$@"

RECEIVE=$RECEIVEJS
if [[ ! -f "${RECEIVE}" ]]; then
  RECEIVE=$RECEIVEPY
  command -v $RECEIVE >/dev/null 2>&1 || {
    RECEIVE="./$RECEIVE"
    if [[ ! -f "${RECEIVE}" ]]; then
      echo "File $RECEIVE does not exist."
      exit 1
    fi
  }
fi

if [[ $ARGS == "" ]]; then
  ARGS="-b 0.0.0.0"
fi

for argument in "$@"; do
  case "$argument" in
  -D|--daemon)
    echo "Daemon is not allowed. You can do that with \`receive.py -D\`."
    exit 1
    ;;
  esac
done

until echo "Running \`$RECEIVE $ARGS\`..." && $RECEIVE $ARGS; do
  echo "receive crashed with exit code $?. Respawning in 3 seconds..." >&2
  sleep 3
done

exit 0
