#!/bin/bash

set -e

waiting() {
  while : ; do
    echo -n "."
    sleep 1
  done
}

export NODE_ENV=production
echo -n "Compiling assets for production"
waiting &
waitingpid=$!
grunt production > /dev/null
kill -9 $waitingpid
echo " Done."

CMD="node xen-mon-app.js"

until echo "Running \`$CMD\`..." && $CMD; do
  echo "\`$CMD\` crashed with exit code $?. Respawning in 3 seconds..." >&2
  sleep 3
done

exit 0
