#!/bin/bash

command -v grunt >/dev/null 2>&1 || {
  echo "You need to install grunt first:"
  echo "  npm -g i grunt-cli"
  exit 1
}

ARGS="$@"

waiting() {
  while : ; do
    echo -n "."
    sleep 1
  done
}

export NODE_ENV=production
echo -n "Compiling assets for production"
waiting &
waitingpid=$!
grunt production >/dev/null
kill -9 $waitingpid
echo " Done."

CMD="node xen-mon-app.js"

until echo "Running \`$CMD $ARGS\`..." && $CMD $ARGS; do
  echo "$CMD $ARGS crashed with exit code $?. Respawning in 3 seconds..." >&2
  sleep 3
done

exit 0
